### ISSUE TITLE
The "key" argument must be one of type string, TypedArray or DataView. Received type object.

### ISSUE THREAD

**Issue by michelalbers** [TinEye/tineye-api-node#21]
I tried to migrate to version 2 of the tineye api and use the following code:

```typescript
import { Bugsnag } from "@bugsnag/js";
const TinEye = require("tineye-api");

const isImageStolen = async (url: string, bugsnagClient: Bugsnag.Client) => {
  try {
    const api = new TinEye(
      "https://api.tineye.com/rest/",
      "<my tineye api key>" // yes - double checked the value here
    );
    const {
      results: { matches },
    } = await api.searchUrl(url);
    return matches.length > 0;
  } catch (err) {
    console.log(err);
    bugsnagClient.notify(err);
    return false;
  }
};
```

and receive the following error:

![image](https://user-images.githubusercontent.com/646691/141814527-b85dc7d8-c1db-4ce5-bb71-5670cb9b2865.png)

**Comment by JonathanGuberman** [comment]
HI @michelalbers. From your error message, it appears that you're not using the current version (2.0.0) of the library; the file that the exception is coming from no longer exists in the current version.

Because it's a full point version higher, `npm update` may not have worked, depending on how your `package.json` file is configured. Please make sure that you're up to date with version 2.0.0 and try again.
